### ISSUE TITLE
the LSD Parameters of  config file TUM2.yaml

### ISSUE THREAD

**Issue by weiningwei** [joanpepcompany/MSC-VO#1]
Hello, thank you for the code. But when I use the config file of [TUM2.yaml](https://github.com/joanpepcompany/MSC-VO/blob/main/Examples/RGB-D/TUM2.yaml), I met the Segmentation fault (core dumped) error. So I think you forget the LSD Parameters in the [TUM2.yaml](https://github.com/joanpepcompany/MSC-VO/blob/main/Examples/RGB-D/TUM2.yaml), that other config files have the LSD Parameters .
#--------------------------------------------------------------------------------------------
# LSD Parameters
#--------------------------------------------------------------------------------------------

LINEextractor.nLevels: 1
LINEextractor.scaleFactor: 1.2
LINEextractor.nFeatures: 200
LINEextractor.min_line_length: 5

**Comment by joanpepcompany** [comment]
Hello, thanks to you for using MSC-VO. You are right, I have only used the TUM3 and the ICL-NUIM to evaluate the system, and the rest of the yaml files are not complete. Moreover, more details of MSC-VO can be found in the paper that we have just uploaded to the arXiv. The link is https://arxiv.org/pdf/2111.03408.pdf
