### ISSUE TITLE
Linking CXX executable ../Examples/RGB-D/rgbd_tum ../lib/libORB_SLAM2.so: undefined reference to `cv::line_descriptor::BinaryDescriptor::compute

### ISSUE THREAD

**Issue by tshooting** [joanpepcompany/MSC-VO#2]
Hello dear author, I am using opencv3.2.0, but the following error occurs, do you know how to solve it?
`[100%] Linking CXX executable ../Examples/RGB-D/rgbd_tum
../lib/libORB_SLAM2.so: undefined reference to `cv::line_descriptor::BinaryDescriptor::compute(cv::Mat const&, std::vector<cv::line_descriptor::KeyLine, std::allocator<cv::line_descriptor::KeyLine> >&, cv::Mat&, bool) const'
../lib/libORB_SLAM2.so: undefined reference to `cv::line_descriptor::BinaryDescriptor::createBinaryDescriptor()'
../lib/libORB_SLAM2.so: undefined reference to `cv::line_descriptor::LSDDetector::detect(cv::Mat const&, std::vector<cv::line_descriptor::KeyLine, std::allocator<cv::line_descriptor::KeyLine> >&, int, int, cv::Mat const&)'
../lib/libORB_SLAM2.so: undefined reference to `cv::line_descriptor::LSDDetector::createLSDDetector()'
collect2: error: ld returned 1 exit status
CMakeFiles/rgbd_tum.dir/build.make:178: recipe for target '../Examples/RGB-D/rgbd_tum' failed
make[2]: *** [../Examples/RGB-D/rgbd_tum] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/rgbd_tum.dir/all' failed
`

**Comment by whwh747** [comment]
you need install opencv_contrib with opencv
