### ISSUE TITLE
An error about segmentation error during running MSC-VO code

### ISSUE THREAD

**Issue by Zhangzhh-107** [joanpepcompany/MSC-VO#3]
Hello dear author, I am trying to running the code of MSC-VO. During the process of configuring environment, there always exists segmentation error. After debug, I found that this segmentation error is loacte in Optimizer::LineOptStruct, if I delete the calling of this function in 277 of Tracking.cc, the algorithm can run successfully. I add an output at the end of Optimizer::LineOptStruct and 278 of Tracking.cc, only the output in Optimizer::LineOptStruct can be print, which means that the segmentation error maybe caused by the memory reclamation of Optimizer::LineOptStruct.I would like to know that is this problem happens when you run this code. If this problem also happened in your device, how can i solve it?
Thank you so much!

**Comment by joanpepcompany** [comment]
Hi Ayakanoinu, 
Thanks for trying it. I have never experienced the related issue. However, I would like to know if this issues is related to the code or the differences in the libraries used. Can you provide more details about the versions of the libraries installed and the operative system used. Have you tried one of the dataset mentioned in the article? 
Best, 
Joan Pep

**Comment by neilzhuu** [comment]
Hi joanpepcompany,
I got the same problem with the TUM datasets. Here are the details of my runtime environment:
- OS - Ubuntu 20.04.3 LTS
- Eigen - 3.3.7
- OpenCV - 3.4.5
- Pangolin - 0.6

I also tried OpenCV 3.2, but it did not work. I hope you could offer some ideas for solutions.
Thank you  so much!

**Comment by Zhangzhh-107** [comment]
> Hi Ayakanoinu, Thanks for trying it. I have never experienced the related issue. However, I would like to know if this issues is related to the code or the differences in the libraries used. Can you provide more details about the versions of the libraries installed and the operative system used. Have you tried one of the dataset mentioned in the article? Best, Joan Pep

Sorry Joan. It is so appologize that i didn't notice the reply of you. I have resolved this problem by adding "return 1" at the end of function LineOptStruct in Optimizer.cc. I think this problem is caused by the c++ library of my computer. Function LineOptStruct is defined as a function with integer return value. But there is no return statement in code. It is hard to explain why but i really solve this problem by adding "return 1" in the end of this function.

**Comment by coutrol** [comment]
> > 嗨，Ayakanoinu，感谢您的尝试。我从未遇到过相关问题。但是，我想知道此问题是否与代码或所用库的差异有关。您能否提供有关已安装的库版本和使用的作系统的更多详细信息。您是否尝试过文章中提到的数据集之一？最佳，琼·佩普
> 
> 对不起，琼。太抱歉了，我没有注意到你的回答。我通过在 Optimizer.cc 函数 LineOptStruct 的末尾添加“return 1”来解决此问题。我认为这个问题是由我电脑的 c++ 库引起的。函数 LineOptStruct 定义为具有整数返回值的函数。但是代码中没有 return 语句。很难解释为什么，但我通过在此函数的末尾添加“return 1”来真正解决了这个问题。

我的系统是ubuntu20.04，opencv4.2，eigen3.3，同样遇到了这个问题，您还记得您是怎么解决的吗
